# Created using wingetcreate 1.5.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Cockos.ReaPlugs
PackageVersion: "2.36"
Platform:
- Windows.Desktop
MinimumOSVersion: 5.1.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSuccessCodes:
- 1223
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://www.reaper.fm/reaplugs/reaplugs236_x64-install.exe
  InstallerSha256: 1654F1F78D746FC87A6F6D078A8F928EA61C7B49997B1F2C07DFC870F8FA6C10
- Architecture: x86
  InstallerUrl: https://www.reaper.fm/reaplugs/reaplugs236-install.exe
  InstallerSha256: 511DBC77E24EDFDC90D08E07DEFCA40063F46F5A1F8E9E6C75F6FFBD161B3E3B
ManifestType: installer
ManifestVersion: 1.5.0
